name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - run: pnpm i

      - run: pnpm run lint

  type:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        typescript-version: [~5.8.3, ~5.9.3]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - run: yq -i '.overrides.typescript = "${{ matrix.typescript-version }}"' pnpm-workspace.yaml

      - run: pnpm i --no-frozen-lockfile

      - run: pnpm run type:check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.21.1, 24.11.1]
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - run: yq -i '.useNodeVersion = "${{ matrix.node-version }}"' pnpm-workspace.yaml

      - run: pnpm i

      - run: pnpm run test:coverage

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
